name: Deploy Flask App to GKE using Artifact Registry

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted,runner-1a]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: sanjeev16-01
          export_default_credentials: true

      - name: Authenticate gcloud account
        run: |
          gcloud config list
          gcloud auth list

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Test Docker installation
        run: docker run --rm busybox date

      - name: Check cloud-sdk in apt sources
        run: grep -rhE ^deb /etc/apt/sources.list* | grep "cloud-sdk"

      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Check kubectl version
        run: kubectl version --client

      - name: Install gke-gcloud-auth-plugin
        run: |
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Check gke-gcloud-auth-plugin version
        run: gke-gcloud-auth-plugin --version

      - name: Install Node.js
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs
          sudo ln -sf /usr/bin/nodejs /usr/local/bin/node

      - name: Install unzip
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/sanjeev16-01/flask-app-repo/flask-app:latest ./app

      - name: Push Docker image to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/sanjeev16-01/flask-app-repo/flask-app:latest

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials private-gke-cluster \
            --region us-central1 \
            --project sanjeev16-01
          
      - name: Deploy to GKE
        run: kubectl apply -f app/app.yml --validate=false
            
      - name: Check cluster access
        run: kubectl get pods
            




# name: Deploy Flask App to GKE using Artifact Registry

# on:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#     runs-on: [self-hosted,runner-1a]

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Set up gcloud CLI
#         uses: google-github-actions/setup-gcloud@v1
#         with:
#           service_account_key: ${{ secrets.GCP_SA_KEY }}
#           project_id: sanjeev16-01
#           export_default_credentials: true

#       - name: authenticate details od account
#         run: |
#           gcloud config list
#           gcloud auth list

#       - name: Build Docker image
#         run: |
#           docker build -t us-central1-docker.pkg.dev/sanjeev16-01/flask-app-repo/flask-app:latest ./app

#       - name: Push Docker image to Artifact Registry
#         run: |
#           docker push us-central1-docker.pkg.dev/sanjeev16-01/flask-app-repo/flask-app:latest

#       - name: Install gke-gcloud-auth-plugin
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

#       - name: Get GKE credentials
#         run: |
#           gcloud container clusters get-credentials private-gke-cluster \
#             --region us-central1 \
#             --project sanjeev16-01

#       # - name: check cluster access
#       #   run: kubectl get nodes

#       - name: Deploy to GKE
#         run: kubectl apply -f app/app.yml --validate=false